# Generated by Django 4.0.1 on 2022-01-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_book_description_alter_book_g_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
