# Generated by Django 4.0.1 on 2022-01-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_alter_author_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
