# Generated by Django 4.0.1 on 2022-01-19 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_alter_author_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelf',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='favourites',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='vote',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
