# Generated by Django 4.0.1 on 2022-01-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_profile_remove_bookshelf_user_remove_favourites_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finder.profile'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finder.profile'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finder.profile'),
        ),
    ]
