# Generated by Django 4.0.1 on 2022-01-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_alter_bookshelf_profile_alter_favourites_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='books',
        ),
        migrations.RemoveField(
            model_name='favourites',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='books',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='bookshelf',
            field=models.ManyToManyField(related_name='profile_shelf', to='finder.Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(related_name='profile_fav', to='finder.Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(related_name='profile_wish', to='finder.Book'),
        ),
        migrations.AddField(
            model_name='vote',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finder.profile'),
        ),
        migrations.DeleteModel(
            name='Bookshelf',
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
