# Generated by Django 4.0.1 on 2022-01-20 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_remove_favourites_books_remove_favourites_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.profile'),
        ),
    ]
