# Generated by Django 4.0.1 on 2022-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_alter_vote_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bookshelf',
            field=models.ManyToManyField(blank=True, related_name='profile_shelf', to='finder.Book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='profile_fav', to='finder.Book'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='profile_wish', to='finder.Book'),
        ),
    ]
