# Generated by Django 4.0.1 on 2022-01-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_alter_profile_bookshelf_alter_profile_favourites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wishlist',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, to='finder.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='finder.Category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finder.publisher'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bookshelf',
            field=models.ManyToManyField(blank=True, related_name='bookshelf', to='finder.Book'),
        ),
    ]
