# Generated by Django 4.0.1 on 2022-01-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0012_alter_book_authors_alter_book_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bookshelf',
        ),
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(blank=True, to='finder.Book'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
