# Generated by Django 4.0.1 on 2022-01-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0013_remove_profile_bookshelf_profile_books_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True),
        ),
    ]
