# Generated by Django 4.0.1 on 2022-01-29 20:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0014_alter_vote_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='added_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finder.profile'),
        ),
        migrations.AddField(
            model_name='author',
            name='added_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='book',
            name='added_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finder.profile'),
        ),
        migrations.AddField(
            model_name='book',
            name='added_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='category',
            name='added_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finder.profile'),
        ),
        migrations.AddField(
            model_name='category',
            name='added_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='publisher',
            name='added_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finder.profile'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='added_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
