# Generated by Django 4.0.1 on 2022-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0017_alter_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='finder.Profile'),
        ),
    ]
