# Generated by Django 4.0.1 on 2022-07-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0019_alter_profile_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn13',
            new_name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn10',
        ),
    ]
